modify script to adapt not only one benchmark

diff --git a/scripts/setup-tpch-db b/scripts/setup-tpch-db
--- a/scripts/setup-tpch-db
+++ b/scripts/setup-tpch-db
@@ -1,28 +1,30 @@
 #!/bin/bash
 #
-# setup-tpch-db
+# setup-monetdb
 #
-# A script for setting up a DB with MonetDB containing the TPC-H schema
+# A script for setting up a DB with MonetDB containing the TPC-H and IMDB_JOB schema
 # and generated data set (with user-specified scale factor). Must be run
 # after MonetDB itself has been properly installed and is available in the
 # executable search path
 #
 #################################################################################
 # By Eyal Rozenberg <eyalroz@technion.ac.il>
-##################################################################################
+#################################################################################
+# Edit by Pei Mu <ds1231h@gmail.com>
+#################################################################################
 #
 
 #------------------------------
 # Helper functions
 
 function usage {
-	REPOSITORY_URL="https://github.com/eyalroz/tpch-tools"
+	REPOSITORY_URL="https://github.com/PeiMu/tpch-monet"
 	echo "Usage: $0 [OPTIONS...]"
-	echo "Downloads, build and installs MonetDB and the dbgen utlilities; generates TPC-H"
+	echo "Downloads, build and installs MonetDB and the dbgen utlilities; generates TPC-H and JOB"
 	echo "data, creates a DB farm, creates a DB and loads the data there."
 	echo
 	echo "Options:"
-	echo "  -r, --recreate              If the TPC-H database exists, recreate it, dropping"
+	echo "  -r, --recreate              If the database exists, recreate it, dropping"
 	echo "                              all existing data. (If this option is unset, the "
 	echo "                              database must not already exist)"
 	echo "  -s, --scale-factor FACTOR   The amount of test data to generate, in GB"
@@ -43,6 +45,7 @@ function usage {
 	echo "  -k, --keep-raw-tables       Keep the raw data generated by the tool outside of"
 	echo "                              the DBMS"
 	echo "  -v, --verbose               Be verbose"
+	echo "	-b, --benchmark BENCHMAKR   Name of the benchmark, e.g. TPC-H, JOB, etc. [unsupported yet]"
 	echo
 	echo "For more information, for feedback and for bug reports - please visit this tool's"
 	echo "source repository online at $REPOSITORY_URL ."
@@ -144,6 +147,7 @@ data_generation_dir="${PWD}/tpch_generated_tables_${TODAY}"
 log_file="${0}.log"
 keep_raw_tables=
 port=50000
+benchmark=TPC-H
 
 #------------------------------
 # Parse command line here
@@ -201,6 +205,10 @@ while [[ $# > 0 ]]; do
 	-k|--keep-raw-tables|--keep-raw)
 		keep_raw_tables=1
 		;;
+	-b|--benchmark)
+		benchmark="$2"
+		shift # past argument
+                ;;
 	*) # unknown option
 		echo "Unknown command line option $option_key" 1>&2
 		break
@@ -274,112 +282,6 @@ fi
 
 # Note: We don't really need that extra space, but... better be on the safe side (especially if the .tbl directory and the DB farm are on the same partition)
 necessary_space_in_gb=$(( 2 * $scale_factor ))
-read -r -d '' schema_creation_sql << EOF
-START TRANSACTION;
-
-CREATE TABLE REGION  (  R_REGIONKEY  INTEGER NOT NULL,
-                        R_NAME       CHAR(25) NOT NULL,
-                        R_COMMENT    VARCHAR(152),
-                        PRIMARY KEY  (R_REGIONKEY));
-
-CREATE TABLE NATION  (  N_NATIONKEY  INTEGER NOT NULL,
-                        N_NAME       CHAR(25) NOT NULL,
-                        N_REGIONKEY  INTEGER NOT NULL,
-                        N_COMMENT    VARCHAR(152),
-                        PRIMARY KEY  (N_NATIONKEY),
-                        FOREIGN KEY (N_REGIONKEY) references REGION);
-
-CREATE TABLE PART  (    P_PARTKEY     INTEGER NOT NULL,
-                        P_NAME        VARCHAR(55) NOT NULL,
-                        P_MFGR        CHAR(25) NOT NULL,
-                        P_BRAND       CHAR(10) NOT NULL,
-                        P_TYPE        VARCHAR(25) NOT NULL,
-                        P_SIZE        INTEGER NOT NULL,
-                        P_CONTAINER   CHAR(10) NOT NULL,
-                        P_RETAILPRICE DECIMAL(15,2) NOT NULL,
-                        P_COMMENT     VARCHAR(23) NOT NULL,
-                        PRIMARY KEY   (P_PARTKEY) );
-
-CREATE TABLE SUPPLIER ( S_SUPPKEY     INTEGER NOT NULL,
-                        S_NAME        CHAR(25) NOT NULL,
-                        S_ADDRESS     VARCHAR(40) NOT NULL,
-                        S_NATIONKEY   INTEGER NOT NULL,
-                        S_PHONE       CHAR(15) NOT NULL,
-                        S_ACCTBAL     DECIMAL(15,2) NOT NULL,
-                        S_COMMENT     VARCHAR(101) NOT NULL,
-                        PRIMARY KEY   (S_SUPPKEY),
-                        FOREIGN KEY (S_NATIONKEY) references NATION);
-
-CREATE TABLE PARTSUPP ( PS_PARTKEY     INTEGER NOT NULL,
-                        PS_SUPPKEY     INTEGER NOT NULL,
-                        PS_AVAILQTY    INTEGER NOT NULL,
-                        PS_SUPPLYCOST  DECIMAL(15,2)  NOT NULL,
-                        PS_COMMENT     VARCHAR(199) NOT NULL,
-                        PRIMARY KEY    (PS_PARTKEY,PS_SUPPKEY),
-                        FOREIGN KEY (PS_SUPPKEY) references SUPPLIER,
-                        FOREIGN KEY (PS_PARTKEY) references PART );
-
-CREATE TABLE CUSTOMER ( C_CUSTKEY     INTEGER NOT NULL,
-                        C_NAME        VARCHAR(25) NOT NULL,
-                        C_ADDRESS     VARCHAR(40) NOT NULL,
-                        C_NATIONKEY   INTEGER NOT NULL,
-                        C_PHONE       CHAR(15) NOT NULL,
-                        C_ACCTBAL     DECIMAL(15,2)   NOT NULL,
-                        C_MKTSEGMENT  CHAR(10) NOT NULL,
-                        C_COMMENT     VARCHAR(117) NOT NULL,
-                        PRIMARY KEY   (C_CUSTKEY),
-                        FOREIGN KEY (C_NATIONKEY) references NATION);
-
-CREATE TABLE ORDERS  (  O_ORDERKEY       INTEGER NOT NULL,
-                        O_CUSTKEY        INTEGER NOT NULL,
-                        O_ORDERSTATUS    CHAR(1) NOT NULL,
-                        O_TOTALPRICE     DECIMAL(15,2) NOT NULL,
-                        O_ORDERDATE      DATE NOT NULL,
-                        O_ORDERPRIORITY  CHAR(15) NOT NULL,
-                        O_CLERK          CHAR(15) NOT NULL,
-                        O_SHIPPRIORITY   INTEGER NOT NULL,
-                        O_COMMENT        VARCHAR(79) NOT NULL,
-                        PRIMARY KEY      (O_ORDERKEY),
-                        FOREIGN KEY (O_CUSTKEY) references CUSTOMER);
-
-CREATE TABLE LINEITEM ( L_ORDERKEY    INTEGER NOT NULL,
-                        L_PARTKEY     INTEGER NOT NULL,
-                        L_SUPPKEY     INTEGER NOT NULL,
-                        L_LINENUMBER  INTEGER NOT NULL,
-                        L_QUANTITY    DECIMAL(15,2) NOT NULL,
-                        L_EXTENDEDPRICE  DECIMAL(15,2) NOT NULL,
-                        L_DISCOUNT    DECIMAL(15,2) NOT NULL,
-                        L_TAX         DECIMAL(15,2) NOT NULL,
-                        L_RETURNFLAG  CHAR(1) NOT NULL,
-                        L_LINESTATUS  CHAR(1) NOT NULL,
-                        L_SHIPDATE    DATE NOT NULL,
-                        L_COMMITDATE  DATE NOT NULL,
-                        L_RECEIPTDATE DATE NOT NULL,
-                        L_SHIPINSTRUCT CHAR(25) NOT NULL,
-                        L_SHIPMODE     CHAR(10) NOT NULL,
-                        L_COMMENT      VARCHAR(44) NOT NULL,
-                        PRIMARY KEY    (L_ORDERKEY,L_LINENUMBER),
-                        FOREIGN KEY (L_ORDERKEY) references ORDERS,
-                        FOREIGN KEY (L_PARTKEY,L_SUPPKEY) references PARTSUPP);
-
-COMMIT;
-EOF
-# ... that was schema_creation_sql
-
-read -r -d '' table_loading_sql_template << EOF
-START TRANSACTION;
-COPY INTO region    from 'PWD/region.tbl'   USING DELIMITERS '|', '\n';
-COPY INTO nation    from 'PWD/nation.tbl'   USING DELIMITERS '|', '\n';
-COPY INTO supplier  from 'PWD/supplier.tbl' USING DELIMITERS '|', '\n';
-COPY INTO customer  from 'PWD/customer.tbl' USING DELIMITERS '|', '\n';
-COPY INTO part      from 'PWD/part.tbl'     USING DELIMITERS '|', '\n';
-COPY INTO partsupp  from 'PWD/partsupp.tbl' USING DELIMITERS '|', '\n';
-COPY INTO orders    from 'PWD/orders.tbl'   USING DELIMITERS '|', '\n';
-COPY INTO lineitem  from 'PWD/lineitem.tbl' USING DELIMITERS '|', '\n';
-COMMIT;
-EOF
-escaped_data_generation_dir=$(echo $data_generation_dir | sed 's/\//\\\//g')
-table_loading_sql=$(echo "$table_loading_sql_template" | sed -e "s/PWD/$escaped_data_generation_dir/")
 
 # Check for binaries
 
@@ -451,29 +353,50 @@ if [[ "$need_to_create_the_db" ]]; then
 		( [[ "$be_verbose" ]] && echo "monetdb -p $port release $db_name" ;  monetdb -p $port release $db_name > /dev/null )
 	) || die "Failed to create (and release) a database named $db_name in DB farm $db_farm"
 	[[ "$be_verbose" ]] && echo "Populating the schema of database $db_name"
-	run_mclient "$schema_creation_sql"
+	if [[ "$benchmark" = "TPC-H" ]]; then
+		create_without_constraints=$(cat tpch_setup/create_without_constraints.sql)
+		echo "$create_without_constraints"
+		run_mclient "$create_without_constraints"
+		add_key_constraints=$(cat tpch_setup/add_key_constraints.sql)
+		echo "$add_key_constraints"
+		run_mclient "$add_key_constraints"
+	elif [[ "$benchmark" = "JOB" ]]; then
+		echo "todo: create table"
+	fi
 fi
 
 # Generate the TPC-H data
 
-if [[ -z "$already_generated" ]] ; then
-pushd $data_generation_dir >/dev/null
+if [[ "$benchmark" = "TPC-H" ]]; then
+	if [[ -z "$already_generated" ]] ; then
+	pushd $data_generation_dir >/dev/null
 	
-	[[ "$be_verbose" ]] && dbgen_verbosity_option="-v"
-	[[ "$be_verbose" ]] && echo "$dbgen_binary -v -b $dbgen_dists_file -s $scale_factor"
-	$dbgen_binary -b $dbgen_dists_file -s $scale_factor $dbgen_verbosity_option || die "Failed generating TPC-H data using $dbgen_binary with scale factor $scale_factor, at $data_generation_dir"
-	popd >&/dev/null
-else
-	[[ -d $data_generation_dir ]] || die "Pre-generated data directory $data_generation_dir is missing"
+		[[ "$be_verbose" ]] && dbgen_verbosity_option="-v"
+		[[ "$be_verbose" ]] && echo "$dbgen_binary -v -b $dbgen_dists_file -s $scale_factor"
+		$dbgen_binary -b $dbgen_dists_file -s $scale_factor $dbgen_verbosity_option || die "Failed generating TPC-H data using $dbgen_binary with scale factor $scale_factor, at $data_generation_dir"
+		popd >&/dev/null
+	else
+		[[ -d $data_generation_dir ]] || die "Pre-generated data directory $data_generation_dir is missing"
+	fi
 fi
 
 # Data generation is complete, time to load it
-for table_name in region nation supplier customer part partsupp orders lineitem; do
-	table_file="$data_generation_dir/${table_name}.tbl"
-	[[ -r $table_file ]] || die "Could not find the generated data file ${table_file} - perhaps its generation failed?"
-done
+if [[ "$benchmark" = "TPC-H" ]]; then
+	for table_name in region nation supplier customer part partsupp orders lineitem; do
+		table_file="$data_generation_dir/${table_name}.tbl"
+		[[ -r $table_file ]] || die "Could not find the generated data file ${table_file} - perhaps its generation failed?"
+	done
+fi
+
 [[ "$be_verbose" ]] && echo "Loading generated data from $data_generation_dir"
 output_format=$( [[ "$be_verbose" ]] && echo "csv" || echo "trash" )
-run_mclient "$table_loading_sql" $output_format
+
+if [[ "$benchmark" = "TPC-H" ]]; then
+	load_data=$(cat tpch_setup/load_data.sql)
+	echo "$load_data"
+	run_mclient "$load_data" $output_format
+elif [[ "$benchmark" = "JOB"  ]]; then
+	echo "todo: load data"
+fi
 
 [[ -n "$keep_raw_tables" ]] || rm -r $data_generation_dir
